# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-11 13:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0002_auto_20160528_1534'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='party',
            field=models.CharField(blank=True, choices=[('D', 'Democratic'), ('R', 'Republican'), ('L', 'Libertarian'), ('G', 'Green'), ('O', 'Other')], max_length=10),
        ),
    ]
