# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-26 14:15
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0003_userinfo_party'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='dob',
            field=models.DateField(default=datetime.datetime(2016, 7, 26, 14, 15, 20, 702275, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userinfo',
            name='phone',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
