# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-26 14:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0004_auto_20160726_1415'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='dob',
            field=models.DateField(blank=True),
        ),
    ]
